
email: ""
baseurl: "/property-data-poc" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed

t:
  en:
    title: Land and Property Data
    phase: Proof of concept
    language: English
    root: /en
    email: dataproject@wra.gov.wales
    feedback: Give feedback
    subscribe: Subscribe now
    archive: View archive
    weeknotes: Weeknotes
    weeknotes_description: Each week we share a short update on what we’re learning, along with links to things we think are interesting or relevant.
    prototype: Prototype
    prototype_title: Prototyping the land and property tax platform
    prototype_one_liner: During the 2nd phase we built a number of prototypes to test our assumptions, platform capability and ideas.
    prototype_link: Read about the prototypes we built
  cy:
    title: Data tir ac eiddo
    phase: Prawf o gysyniad
    language: Cymraeg
    root: /cy
    email: prosiect.dataeiddo@acc.llyw.cymru
    feedback: Rhowch eich adborth
    subscribe: Tanysgrifiwch nawr
    archive: Gweld archif
    weeknotes: Nodiadau wythnosol
    weeknotes_description: Bob wythnos rydym yn rhannu diweddariad byr ar yr hyn rydym yn ei ddysgu, ynghyd â dolenni i bethau sydd, yn ein barn ni, yn ddiddorol neu'n berthnasol.
    prototype: Prototeip
    prototype_title: Prototeipio'r llwyfan treth tir ac eiddo
    prototype_one_liner: Yn ystod yr 2il gam fe wnaethom adeiladu nifer o brototeipiau i brofi ein rhagdybiaethau, gallu platfform a syniadau.
    prototype_link: Darllenwch am y prototeipiau a adeiladwyd gennym