
email: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed

t:
  en:
    title: Land and Property Data
    description:
    phase: Proof of concept
    language: English
    root: /en
  cy:
    title: Data tir ac eiddo
    description:
    phase: Prawf o gysyniad
    language: Cymraeg
    root: /cy
